language: generic
env:
  global:
  # Set defaults to avoid repeating in most cases  
  - PYTHON_VERSION=$TRAVIS_PYTHON_VERSION
  - MAIN_CMD='python setup.py'
  #- CONDA_DEPENDENCIES='sphinx pillow pyproj coveralls coverage mock aggdraw six pyshp pyresample'
  - PIP_DEPENDENCIES=''
  - SETUP_XVFB=False
  - EVENT_TYPE='push pull_request'
  - SETUP_CMD='test'
  - CONDA_CHANNELS='conda-forge'
  - CONDA_CHANNEL_PRIORITY='True'
matrix:
  include:
  - env:
    - PYTHON_VERSION=2.7
    - NUMPY_VERSION=1.16
    arch: ppc64le
    dist: bionic
    os: linux
  - env: PYTHON_VERSION=3.6
    os: linux
    arch: ppc64le
    dist: focal
  - env: PYTHON_VERSION=3.7
    os: linux
    dist: focal
    arch: ppc64le
before_install:
  - if [[ "$TRAVIS_CPU_ARCH" == "ppc64le" ]]; then 
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-ppc64le.sh -O miniconda.sh;
    else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes
  - conda config --set auto_update_conda False
  - conda update -q --all
  - conda install python=$PYTHON_VERSION pip
install:
  - pip   install aggdraw --no-cache-dir
  - conda install coverage
  - conda install coveralls
  - conda install mock pillow 
  - pip install pyproj --no-cache-dir
  - pip   install pyresample --no-cache-dir 
  - conda install pyshp sphinx
  - pip install --no-deps -e .
  
script:
  - coverage run --source=pycoast setup.py test

 
after_success:
- if [[ $PYTHON_VERSION == 3.6 ]]; then coveralls; fi
deploy:
- provider: pypi
  user: dhoese
  password:
    secure: M3wCEnirvwNDncuoLj8DpPFwNypLXcDGlAinNHfwZLIEzDTNrC5XhGZ3xbfmAeBGOIgJ2I6xDWJ6hYevv3HxBdgln9nJfO7tsnqisK1lxyF4/dntCJm5CLkJqM8To1o9zeht0dyZJ66fUAHfxwjXGBDoaPyEnsygWXH6vpEZ8K0=
  distributions: sdist
  skip_existing: true
  on:
    tags: true
    repo: pytroll/pycoast
notifications:
  slack: pytroll:96mNSYSI1dBjGyzVXkBT6qFt
